# Generated by Django 5.1.1 on 2024-10-19 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('development', 'Can do development'), ('scrum_master', 'Can do scrum master'), ('product_owner', 'Can do product owner'))},
        ),
    ]
