# Generated by Django 5.1.2 on 2024-11-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_del_proyecto', '0002_fabricante_producto_fabricante'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricante',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='f_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
