# Generated by Django 5.1.2 on 2024-11-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_del_proyecto', '0003_fabricante_pais_producto_f_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricante',
            name='pais',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
