-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.brands
(
    brand_id serial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT brands_pkey PRIMARY KEY (brand_id)
);

CREATE TABLE IF NOT EXISTS public.clients
(
    client_id serial NOT NULL,
    run text COLLATE pg_catalog."default" NOT NULL,
    first_name text COLLATE pg_catalog."default" NOT NULL,
    last_name text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default" NOT NULL,
    phone integer NOT NULL,
    client_status text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT clients_pkey PRIMARY KEY (client_id)
);

CREATE TABLE IF NOT EXISTS public.jobs
(
    job_id serial NOT NULL,
    maintenance_id integer NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    labor_rate real NOT NULL,
    parts_cost real NOT NULL,
    CONSTRAINT jobs_pkey PRIMARY KEY (job_id)
);

CREATE TABLE IF NOT EXISTS public.maintenances
(
    maintenance_id serial NOT NULL,
    date time with time zone NOT NULL,
    CONSTRAINT maintenances_pkey PRIMARY KEY (maintenance_id)
);

CREATE TABLE IF NOT EXISTS public.models
(
    model_id serial NOT NULL,
    model_name text COLLATE pg_catalog."default" NOT NULL,
    model_year integer NOT NULL,
    CONSTRAINT models_pkey PRIMARY KEY (model_id)
);

CREATE TABLE IF NOT EXISTS public.sales
(
    sale_id serial NOT NULL,
    total_amount numeric NOT NULL,
    date time with time zone NOT NULL,
    client_id integer NOT NULL,
    CONSTRAINT sales_pkey PRIMARY KEY (sale_id)
);

CREATE TABLE IF NOT EXISTS public.sales_maintenances_details
(
    sales_maintenance_detail_id serial NOT NULL,
    sale_id integer NOT NULL,
    maintenance_id integer NOT NULL,
    price numeric NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT sales_maintenances_details_pkey PRIMARY KEY (sales_maintenance_detail_id)
);

CREATE TABLE IF NOT EXISTS public.sales_vehicles_details
(
    sale_vehicle_detail_id serial NOT NULL,
    sale_id integer NOT NULL,
    vehicle_id integer NOT NULL,
    CONSTRAINT sales_vehicles_details_pkey PRIMARY KEY (sale_vehicle_detail_id)
);

CREATE TABLE IF NOT EXISTS public.vehicles
(
    vehicle_id serial NOT NULL,
    patent text COLLATE pg_catalog."default" NOT NULL,
    price numeric NOT NULL,
    vehicle_type_id integer NOT NULL,
    color text COLLATE pg_catalog."default" NOT NULL,
    brand_id integer NOT NULL,
    maintenance_frequency_kms integer NOT NULL,
    model_id integer NOT NULL,
    CONSTRAINT vehicles_pkey PRIMARY KEY (vehicle_id)
);

CREATE TABLE IF NOT EXISTS public.vehicles_types
(
    vehicle_type_id serial NOT NULL,
    vehicle_type text NOT NULL,
    PRIMARY KEY (vehicle_type_id)
);

ALTER TABLE IF EXISTS public.jobs
    ADD CONSTRAINT jobs_maintenances_maintenance_id FOREIGN KEY (maintenance_id)
    REFERENCES public.maintenances (maintenance_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales
    ADD CONSTRAINT fk_sales_clients_client_id FOREIGN KEY (client_id)
    REFERENCES public.clients (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_maintenances_details
    ADD CONSTRAINT fk_sales_maintenances_details_maintenances_maintenance_id FOREIGN KEY (maintenance_id)
    REFERENCES public.maintenances (maintenance_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_maintenances_details
    ADD CONSTRAINT fk_sales_maintenances_details_sales_sale_id FOREIGN KEY (sale_id)
    REFERENCES public.sales (sale_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_vehicles_details
    ADD CONSTRAINT fk_sales_vehicles_details_sales_sales_id FOREIGN KEY (sale_id)
    REFERENCES public.sales (sale_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_vehicles_details
    ADD CONSTRAINT fk_sales_vehicles_details_vehicles_vehicle_id FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicles (vehicle_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vehicles
    ADD CONSTRAINT fk_vehicles_brands_brand_id FOREIGN KEY (brand_id)
    REFERENCES public.brands (brand_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vehicles
    ADD CONSTRAINT fk_vehicles_models_model_id FOREIGN KEY (model_id)
    REFERENCES public.models (model_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vehicles
    ADD CONSTRAINT fk_vehicles_vehicles_types_vehicle_type_id FOREIGN KEY (vehicle_type_id)
    REFERENCES public.vehicles_types (vehicle_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;