# Generated by Django 5.1.1 on 2024-10-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('BEBIDA_CALIENTE', 'Bebida Caliente'), ('BEBIDA_FRIA', 'Bebida Fría'), ('POSTRE', 'Postre'), ('SNACK', 'Snack'), ('SANDWICH', 'Sandwich')], default='BEBIDA_CALIENTE', max_length=50),
        ),
    ]
